export type Project = {
  title: string
  description: string
  technologies: string[]
  roleBullets: string[]
  githubUrl?: string
  liveUrl?: string
}

export const projects: Project[] = [
  {
    title: 'Application Role Management System (ARMS)',
    description:
      'A production-grade backend API built with Clean Architecture principles to manage multi-application role-based access control (RBAC). Administrators can register applications, define permission groups, and assign roles dynamically. Client applications query their authorized access rights at runtime via secure JWT-protected endpoints.',
    technologies: [
      '.NET 9',
      'ASP.NET Core Web API',
      'Entity Framework Core',
      'SQL Server',
      'JWT Authentication',
      'AutoMapper',
      'Clean Architecture',
      'Swagger (OpenAPI)',
    ],
    roleBullets: [
      'Architected the solution using Clean Architecture (API, Application, Domain, Persistence layers)',
      'Implemented JWT-based authentication with role-based and policy-based authorization',
      'Built application approval workflow and dynamic permission assignment endpoints',
      'Configured Swagger UI with Bearer token support for secure API documentation and testing',
      'Managed database schema evolution using EF Core Code-First migrations',
    ],
    githubUrl: '',
  },
  {
    title: 'Hospital Management System',
    description:
      'A full-stack Hospital Management System designed to digitize and streamline core hospital operations. The system handles patient registration and records, appointment scheduling, staff management, and medical data tracking. Built with a RESTful ASP.NET Core backend and a React frontend, backed by a relational database with normalized schema design.',
    technologies: [
      'ASP.NET Core Web API',
      'C#',
      'Entity Framework Core',
      'SQL Server',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'JWT Authentication',
      'REST APIs',
    ],
    roleBullets: [
      'Designed normalized relational database schema for patients, appointments, staff, and medical records',
      'Built RESTful API endpoints for patient CRUD, appointment booking, and staff management',
      'Implemented role-based access control for Admin, Doctor, and Receptionist roles',
      'Developed React frontend with dynamic dashboards for patient and appointment management',
      'Integrated JWT authentication for secure session management across all user roles',
    ],
    githubUrl: '',
  },
  {
    title: 'SaaS Hotel Management System',
    description:
      'A multi-tenant SaaS platform for hotel operations, supporting room inventory management, customer reservations, payment processing, and admin dashboards. Designed with scalability in mind, the system allows multiple hotel clients to operate independently under a shared infrastructure with tenant-isolated data.',
    technologies: [
      'ASP.NET Core Web API',
      'C#',
      'Entity Framework Core',
      'PostgreSQL',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'JWT Authentication',
      'Multi-Tenancy',
      'REST APIs',
    ],
    roleBullets: [
      'Designed multi-tenant architecture with tenant-isolated data access patterns',
      'Built room booking engine with availability checks and conflict prevention logic',
      'Implemented customer management, payment tracking, and invoice generation',
      'Developed admin dashboard with occupancy reports and revenue analytics',
      'Configured PostgreSQL with EF Core and handled schema-per-tenant migrations',
    ],
    githubUrl: '',
  },
  {
    title: 'Smart Health Kiosk – Doctor Web Dashboard (Thesis)',
    description:
      'A Smart Health Kiosk system developed as a thesis project to digitally monitor and manage patient health data. The doctor web dashboard provides secure access to patient vitals, medical history, and health reports generated by the kiosk hardware, enabling remote patient monitoring and data-driven clinical decisions.',
    technologies: [
      'ASP.NET Core',
      'REST APIs',
      'React',
      'Entity Framework Core',
      'JWT Authentication',
      'Database Integration',
    ],
    roleBullets: [
      'Developed the complete doctor web dashboard from design to deployment',
      'Implemented secure authentication and role-based access for medical staff',
      'Integrated backend APIs for real-time patient data and health report retrieval',
      'Designed a responsive, accessible UI optimized for clinical workflows',
    ],
    githubUrl: '',
  },
  {
    title: 'ASTU Course Management Web Application (Team Project)',
    description:
      'A course planning and recommendation platform built for ASTU students. The system enables students to manage course selection, track academic progress, and receive course recommendations through a Flask + SQLite backend and a React + Tailwind CSS frontend.',
    technologies: ['Flask', 'SQLite', 'React', 'Tailwind CSS', 'Vite', 'Python'],
    roleBullets: [
      'Developed the admin dashboard interface for managing courses and student data',
      'Contributed to frontend-backend API integration',
      'Participated in system design, database modeling, and end-to-end testing',
    ],
    githubUrl: '',
  },
  {
    title: 'Bank Exchange Rate Web Scraping Application',
    description:
      'A C# application that automates the collection of real-time exchange rate data from multiple Ethiopian bank websites. The scraper parses dynamic HTML, normalizes the extracted data, and structures it for backend consumption and display.',
    technologies: ['C#', 'ASP.NET', 'HtmlAgilityPack', 'Web Scraping'],
    roleBullets: [
      'Implemented multi-source web scraping logic targeting Ethiopian bank websites',
      'Parsed and normalized dynamic HTML tables using HtmlAgilityPack',
      'Structured extracted exchange rate data for API consumption',
    ],
    githubUrl: '',
  },
]
